name: CI Compilar kernel

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3
        
      - name: Deletar actions antigas com falhas
        run: |
             curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
             -H "Accept: application/vnd.github.v3+json" \
             https://api.github.com/repos/${{ github.repository }}/actions/runs \
             | jq -r '.workflow_runs[] | select(.conclusion == "failure") | .id' \
             | xargs -I {} curl -X DELETE -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
             -H "Accept: application/vnd.github.v3+json" \
             https://api.github.com/repos/${{ github.repository }}/actions/runs/{}
             
      - name: Instalar dependências
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential linux-headers-$(uname -r) libncurses-dev gawk flex bison openssl libssl-dev dkms libelf-dev libudev-dev libpci-dev libiberty-dev autoconf llvm git ccache
        
      - name: Baixar e descompactar o kernel
        run: |
          KERNEL_SOURCE_URL=https://mirrors.edge.kernel.org/pub/linux/kernel/v6.x/linux-6.1.60.tar.xz
          wget $KERNEL_SOURCE_URL
          tar -xf linux-6.1.60.tar.xz

      - name: Chegar Ajuda Kernel
        run: |
          cd linux-6.1.60
          make help
          
      - name: Compilar Kernel 
        run: |
          ls
          cd linux-6.1.60
          make x86_64_defconfig
          make -j$(nproc)
          ls arch/x86/boot/

      - name: Upload de artefatos
        uses: actions/upload-artifact@v2
        with:
          name: kernel-image
          path: linux-6.1.60/arch/x86/boot/bzImage
