name: CI Compilar kernel

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Baixar e descompactar o kernel
        run: |
          KERNEL_SOURCE_URL=https://mirrors.edge.kernel.org/pub/linux/kernel/v6.x/linux-6.1.60.tar.xz
          wget $KERNEL_SOURCE_URL
          tar -xf linux-6.1.60.tar.xz

      - name: Compilar kernel
        run: |
          cd linux-6.1.60
          make help
        #make tinyconfig -j$(nproc)

      - name: Upload de artefatos
        uses: actions/upload-artifact@v2
        with:
          name: kernel-image
          path: linux-6.1.60/arch/x86/boot/bzImage
